# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "2FA Mind"
description: 
url: "http://2faMind.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

owner:
  name: Carina C. Zona
  avatar: carina-c-zona-300x300.jpg
  profile: http://cczona.com/speaking/speaker
  website: http://cczona.com
  email: cczona@gmail.com
  twitter: cczona
  linkedin: cczona
  slideshare: cczona
  youtube_playlist: PL8KPq_fW3yN3l_BRYKaBvcXDOgbPuDrJC
  vimeo_playlist: search?q=%22carina+c+zona%22


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

## non-blogging themes natively supported by Github Pages
# theme: jekyll-theme-cayman
# theme: jekyll-theme-leap-day
# theme: jekyll-theme-midnight
# theme: jekyll-theme-minimal
# theme: jekyll-theme-slate
# theme: jekyll-theme-tactile
# theme: jekyll-theme-time-machine

## **** PREFERRED BLOGGING THEME ****
theme: "leonids"

## other blogging themes
# theme: neo-hpstr-jekyll-theme
# theme: "jekyll-theme-docs"
# theme: jekyll-swiss
# theme: clean-jekyll-theme

## non-blogging themes
# theme: "ovh-jekyll-doc-theme"
# theme: "docs-jekyll-theme"
# theme: "jekyll-materialdocs"



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
